### ISSUE TITLE
[HACKTOBERFEST] PR your React app

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#106]
HACKTOBERFEST is almost about to end, don't be late, just PR your react app to participate hacktoberfest.

add your projects to "PROJECTS" folder
Good Luck,
Always welcome to our family DISCORD [JOIN](https://discord.gg/xwRbDwnbMr)

**Comment by avezqureshi14** [comment]
Ok @devvsakib can you assign me this

**Comment by devvsakib** [comment]
> Ok @devvsakib can you assign me this

suree

**Comment by avezqureshi14** [comment]
Bro @devvsakib  can you tell what actually I have to do

**Comment by devvsakib** [comment]
> 

clone this repository, add your projects in PROJECTS folder. that's it

**Comment by devvsakib** [comment]
@avezqureshi14

**Comment by devvsakib** [comment]
> i also want to add my react project @devvsakib

assigned

**Comment by devvsakib** [comment]
> Hey, Can you assign this to me? I want to add my react project here

sure, assigned

**Comment by devvsakib** [comment]
> Assign me , i want to add my react.js project

assigned

**Comment by Rajiv7479** [comment]
PR Raised

**Comment by PriteshKiri** [comment]
I have raised a PR for this issue

**Comment by devvsakib** [comment]
> I have raised a PR for this issue. Kindly check and merge

marged and hacktoberfest label added🤝🏻

**Comment by Nupoor10** [comment]
Can you assign me this I would like to add my projects

**Comment by devvsakib** [comment]
> Can you assign me this I would like to add my projects

sure

**Comment by kiranrega** [comment]
What type of projects i can add in this repo.

**Comment by devvsakib** [comment]
@kiranrega  any type of project you want.
