### ISSUE TITLE
Add any website clone projects

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#127]
If you ever cloned any well-known website like amazon, netflix, tesla, disney, spotify. you can PR your projects

adding project:
add your projects in "PROJECTS" folder
hacktoberfest label will be added

**Comment by AniqJaved** [comment]
Kindly check the following PR for the netflix clone.
https://github.com/devvsakib/hacktoberfest-react-project/pull/141

**Comment by karthiknadar1204** [comment]
@devvsakib ,i would like to add my project,could you please assign it to me

**Comment by devvsakib** [comment]
assigned @karthiknadar1204

**Comment by devvsakib** [comment]
Hi @karthiknadar1204 , did you added any projects? I'm sorry if I made a mistake.

**Comment by karthiknadar1204** [comment]
Will add the project tomorrow, apologies for the inconvenience @devvsakib

**Comment by devvsakib** [comment]
no worries, I was confused that you may be already added but I didn't close this issue. My bad. Take your time @karthiknadar1204

**Comment by karthiknadar1204** [comment]
Will initiate a pr tomorrow night for this issue and start working on next @devvsakib , apologies for the delay

**Comment by karthiknadar1204** [comment]
@devvsakib ,have added the clone and initiated a pr

**Comment by karthiknadar1204** [comment]
Thank you
