### ISSUE TITLE
SUGGEST FEATURE

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#13]
## Feature Idea
So far everything going well. But now we have to add something really cool. If you have any idea or suggestion please comment here. 

## Already Have ReactJs projects?
If you already have project, then you can add your project in PROJECTS folder and don't forget to comment out your github username and link in your project file

Thank You, Hope for Best

**Comment by amardeep911** [comment]
I can do this. Plz assign this to me

**Comment by Omm2005** [comment]
I can give you Ideas!

**Comment by devvsakib** [comment]
> I can do this. Plz assign this to me

sure

**Comment by Omm2005** [comment]
Is there any specific topic ?

**Comment by devvsakib** [comment]
@Omm2005  we are searching reactjs project and we want to add content in homepage

**Comment by Omm2005** [comment]
Ok also can I also work on react js projects? I have just learned ReactJs!

**Comment by devvsakib** [comment]
> Ok also can I also work on react js projects? I have just learned ReactJs!

yes, if want you can, its an open source project, so feel free to update or change anything
