### ISSUE TITLE
add Frontend Development Guideline to roadmap page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#140]
add some suggestions, guideline to roadmap page

title: frontend 
sub title: frontend roadmap

**Comment by AniqJaved** [comment]
I would like to work on this issue

**Comment by devvsakib** [comment]
> I would like to work on this issue
> 

assigned

**Comment by AniqJaved** [comment]
I would like to have more context on this.

**Comment by devvsakib** [comment]
> I would like to have more context on this.

go for it

**Comment by Pjha72** [comment]
I would like to work on this issue

**Comment by Pjha72** [comment]
I have added frontend roadmap, pls check it.

**Comment by devvsakib** [comment]
@Pjha72  merged
