### ISSUE TITLE
footer text not center aligned on Small device

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#154]
**Describe the bug**
The footer text is not center aligned. you can align it center and get green square
![image](https://user-images.githubusercontent.com/88339569/212750528-7fc73310-2ace-4645-855d-e9f61df921b5.png)

**To Reproduce**
go to footer components and add `text-center`

**Expected behavior**
![image](https://user-images.githubusercontent.com/88339569/212750737-b8218dcf-7b18-4331-8f29-855d8611347a.png)

**Screenshots**
null

**Smartphone (please complete the following information):**
 - Device: Any Mobile
 - Browser : Any
 -

**Comment by JaiS99** [comment]
Please assign this..

**Comment by devvsakib** [comment]
assigned @JaiS99

**Comment by devvsakib** [comment]
well done @JaiS99 ... thanks for contributing. you can leave a start to repository

**Comment by devvsakib** [comment]
fixes #158
