### ISSUE TITLE
add your blog

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#173]
We have a blog page with cards. Now we have to add blogs. If you write blog, then you can add your blog.
![image](https://user-images.githubusercontent.com/88339569/220028000-7d9deaf6-3e5f-4a5f-83e5-3408ce32509e.png)

### How to add Your Blog
You just have to simply add some details to the JSON file.
JSON file location `power-the-web/src/json/Blogs.json`

**what you need**
1. Your blog Thumbnail link
2. Blog Title
3. Descriptions
4. Blog Link

## ***NOTE
please do not upload your thumbnail photo to this repository for your blog.

**Comment by martinyis** [comment]
Hey, do you still need to add blogs? If yes, I am interested to work on this issue.

**Comment by martinyis** [comment]
Oh my bad, I didn't notice that I need to add my personal blog. I am just looking for issues to solve.
