### ISSUE TITLE
Need update in README 

### ISSUE THREAD

**Issue by gulshanpr** [devvsakib/power-the-web#177]
**Describe the bug**
There is no clear instruction for creating a new branch 

**To Reproduce**
In the 'How to Contribute to this repository' after the 4th instruction

**Additional context**
It is always suggested to create a new branch and work on the changes over it.

**Comment by gulshanpr** [comment]
@devvsakib could you assign this to me.

**Comment by devvsakib** [comment]
Assigned @gulshanpr

**Comment by gulshanpr** [comment]
@devvsakib could you review my pull request.

**Comment by devvsakib** [comment]
Merged #178
