### ISSUE TITLE
Side Scroll Bar Request

### ISSUE THREAD

**Issue by FreddyFiend** [devvsakib/power-the-web#180]
My mouse wheel is broken for ages so i use side scroll bar to scroll onto website, but i have no idea why this website doesn't have side scroll bar

**Comment by devvsakib** [comment]
Thank you for raising an issue, we will work on this. And thank you again for letting us know about your case. We hid the scroll bar, you have to point, so we will again add the scroll bar. We didn't think about that before!

**Comment by devvsakib** [comment]
Fixes #181
