### ISSUE TITLE
[SUGGESTION?]: should we use Vite in our existing project?

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#185]
**Is your feature request related to a problem? Please describe.**
Vite and CRA (Create React App) are both tools for building web applications using React. Vite is a relatively new tool that offers faster development and better performance compared to CRA.

we are using CRA build tool. As you know CRA is a little bit slow and takes so much to start the server. If you ever used VITE, you know how fast is Vite. So, I'm considering using Vite.

**Describe alternatives you've considered**
Or we can stick with CRA. I'm not sure about MPA though. cause our site is not MPA. so there will be no problem if we move to Vite. But, your thought, solution is the most priority to us.

**Comment by PiseAtharva** [comment]
Vite is a really good choice for migrating, the only other alternative with your React environment would be Next Js (since its built on React) and its pretty fast as well.

**Comment by devvsakib** [comment]
Thats a great suggestion @PiseAtharva . Most of the people are using Nextjs frameworks

**Comment by PiseAtharva** [comment]
Yeah, NextJS have a documentation on how to [Migrate to Next Environment](https://nextjs.org/docs/migrating/from-create-react-app), and also for [Migrating from React Router](https://nextjs.org/docs/migrating/from-react-router)

**Comment by mukadas026** [comment]
Moving away from CRA is a pretty good idea cus you know, it's slow..... I'd recommend Vite because it's relatively easier to setup and a lot faster.
