### ISSUE TITLE
add margin bottom to contributors page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#187]
**Is your feature request related to a problem? Please describe.**
Add mb-12 in the contributor's page. The footer and contributors' cards look messy
![image](https://user-images.githubusercontent.com/88339569/222809646-913dd161-163d-4ce9-8ef9-70ff75666959.png)

**Comment by an4s911** [comment]
This issue is fixed right?

**Comment by devvsakib** [comment]
> This issue is fixed right?

Yeah, Thanks for the reminder
