### ISSUE TITLE
[FEAT]: add Title and Tagline to blog page 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#188]
**Is your feature request related to a problem? Please describe.**
Our blog page has no title. Add a title and tagline
![image](https://user-images.githubusercontent.com/88339569/222810215-513b4508-bbc7-42ed-9233-b309ea421990.png)

**Describe the solution you'd like**

title: Blogs
tagline: Read more, Gain more. Add your blog!

"Add" must be a link < a > Add </ a >
the link will be pointed to "https://github.com/devvsakib/power-the-web"

**Additional context**
Get green square now!!!

**Comment by devvsakib** [comment]
style:
![image](https://user-images.githubusercontent.com/88339569/222810587-9dfd00ab-83f8-4408-b9f0-3131be8c5e31.png)

**Comment by SalmanShahid888** [comment]
I have added the Blog Title and tagline need some clarification on Add button, is it button or just a link? and do tell me the styles it would utilize

**Comment by devvsakib** [comment]
It's just a link with any color.  use the same style as the other's page has

**Comment by devvsakib** [comment]
completed #193
