### ISSUE TITLE
[FEAT]: add a 404 page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#189]
**Is your feature request related to a problem? Please describe.**
Lmao, we have no 404 page yet! Add a simple Not Found page and link to the home page
![image](https://user-images.githubusercontent.com/88339569/222811224-2484e638-2ab6-4611-bd26-08b2fe554196.png)

**Describe the solution you'd like**
Design as you want. Just need the page to be here.

**Additional context**
Do not take this issue if you are not familiar with `react-router`. Thanks

**Comment by ViLaud** [comment]
Hi @devvsakib, I'd love to tackle this issue. May I get this assigned to me?

**Comment by devvsakib** [comment]
All yours @ViLaud

**Comment by devvsakib** [comment]
Completed #202
