### ISSUE TITLE
[TEAM]: Work on Documentation page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#190]
**Is your feature request related to a problem? Please describe.**
This page address `/guidelines/getstarted/Documents`
![image](https://user-images.githubusercontent.com/88339569/222815300-3924d575-cb0b-4bc5-af13-c7b1bb001f46.png)

We are working on it to add some documents like Interview questions, roadmap etc.

We really need your help. If you want to contribute please feel free to join us.

**Comment by Akbar-Ahmed** [comment]
Hey , can you explain some more about the requirement. What kind of document the project required? Can you elaborate. Thanks.

**Comment by devvsakib** [comment]
@Akbar-Ahmed  There are four categories of documents. When the user clicks, it will expend many options [2nd screenshot]. 
![image](https://user-images.githubusercontent.com/88339569/222897340-a5500f3d-a288-4594-814d-293fdc04b15c.png)

Again, when the user these options, we will show data on the right side.
![image](https://user-images.githubusercontent.com/88339569/222897368-5069e3a0-dd88-4d97-8fa1-3e3a147d3895.png)

It's like tailwindcss.com/docs page.

**Comment by OrlundoHubbard** [comment]
Is the issue about adding more content to the documentation?

**Comment by devvsakib** [comment]
@OrlundoHubbard 

First, we have to do the functionality. As I said if anyone clicks here, we have to show data on the right side. I have prepared some interview questions. But the functionality is not done yet.
https://user-images.githubusercontent.com/88339569/222897368-5069e3a0-dd88-4d97-8fa1-3e3a147d3895.png

If we click HTML:
on the right side, we will show HTML-related questions. that means we will render another component here.
So we have to create components first, right?

**Comment by karthiknadar1204** [comment]
can i try working on this issue?

**Comment by devvsakib** [comment]
sure @karthiknadar1204

**Comment by karthiknadar1204** [comment]
i'll try setting up the project on my system

**Comment by karthiknadar1204** [comment]
could you please guide me on setting the project on my local system,i have cloned the repo on my compiler,this is my second open-source contribution after yesterday.

Thank you

**Comment by devvsakib** [comment]
Sure. You can also follow the guidelines in readme.md file.

go to the project folder you cloned, then open the terminal and run  `npm i && npm run dev`. 
dont

**Comment by karthiknadar1204** [comment]
Thank you so much,will communicate further today evening

**Comment by usernameisleye** [comment]
I would also like to work on this issue @devvsakib🙂
And is there a way you can share your prepared questions or other data?

**Comment by devvsakib** [comment]
> I would also like to work on this issue @devvsakib🙂 And is there a way you can share your prepared questions or other data?

I have, but not in json format. You can use dummy data for now, I will give you later or in 2/3 hour

**Comment by karthiknadar1204** [comment]
i have analysed the code base and the feature to be added,will locate the code for that location(side bar) and merge the pull request soon.

**Comment by devvsakib** [comment]
@karthiknadar1204  @usernameisleye  here's the JSON file you guys can use. 
[JSON LINK](https://github.com/devvsakib/power-the-web/blob/main/src/json/javascriptinterview.json)

**Comment by karthiknadar1204** [comment]
@usernameisleye ,as far as i have come to understand ,its an onclick event to be added to the document,i am trying to figure out how to do that,could you help me with that?

**Comment by devvsakib** [comment]
A little visualization. @Akbar-Ahmed  @usernameisleye  @karthiknadar1204 
![image](https://user-images.githubusercontent.com/88339569/224071890-5def8189-40f3-47be-9618-2b6be4c0a317.png)

First: create components named HTML, CSS so on.

this may work, I didn't check, please check 
```js
const [cssQuestions, setCssQuestions] = useState([]);

  useEffect(() => {
    fetch("javascriptinterview.json")
      .then((response) => response.json())
      .then((data) => {
        const cssQuestions = data.filter((q) => q.tag === "css");
        setCssQuestions(cssQuestions);
      });
  }, []);
```

**Comment by devvsakib** [comment]
Here's the preview #239 

please check and comment if anything need to change

**Comment by usernameisleye** [comment]
Hey @devvsakib, sorry I couldn't deliver quickly. I had a bit of a rough time figuring out the logic and I had some other ongoing projects. I've been reading through your code and I seem to get it a bit more now.

**Comment by devvsakib** [comment]
This issue is completed for now
