### ISSUE TITLE
change the footer UI

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#199]
**Is your feature request related to a problem? Please describe.**
Change the footer UI according to our website. 
![image](https://user-images.githubusercontent.com/88339569/222897559-6e61e5fc-73f8-4ad9-9bb2-f8bd04803fe9.png)

**Describe the solution you'd like**
Maybe blur the background with white text? Just remove the black background color. And try to add a backdrop blur filter. That's it

**Comment by devvsakib** [comment]
Sure @SalmanShahid888

**Comment by SalmanShahid888** [comment]
#203 Fixes the issue Please close.
