### ISSUE TITLE
Overflow on the right side of HomePage

### ISSUE THREAD

**Issue by SalmanShahid888** [devvsakib/power-the-web#200]
**Describe the bug**
OverFlow on the right side of Home Page on Live Website.

**Expected behavior**
There Shouldn't be any overflow on the homepage

**Screenshots**
![image](https://user-images.githubusercontent.com/71010239/222897698-b9a49029-514d-429e-a93a-7b039a4b6c03.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [e.g. chrome]
 - Version [e.g. 22

**Comment by devvsakib** [comment]
it can be fixed by adding `overflow-x-hidden` in the `Home.js` file

**Comment by devvsakib** [comment]
do you want to take this? or I can work on it @SalmanShahid888

**Comment by devvsakib** [comment]
Assigned to you. Thanks
