### ISSUE TITLE
Fix Typo mistake

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#206]
**Describe the bug**
There are a project folder typo mistake in PROJECTS folder
![image](https://user-images.githubusercontent.com/88339569/223116101-9db24337-14a1-4c19-9533-ea8bea8bdb1e.png)

**To Reproduce**
tribute -> tribute

**Screenshots**
added

**Comment by devvsakib** [comment]
assigned @karthiknadar1204

**Comment by karthiknadar1204** [comment]
have fixed the typo=>changed trubute to tribute,will commit changes and initiate pull request as well by day end

**Comment by karthiknadar1204** [comment]
committed the changes
creating a pull request

**Comment by karthiknadar1204** [comment]
done
Thank you

**Comment by devvsakib** [comment]
Thanks for contributing.

Completed #208

**Comment by devvsakib** [comment]
Hi @karthiknadar1204 , You forget to add your details to `Contributors.json` file

path -> `src-json-Contributors.json`

You can make another PR. thanks

**Comment by karthiknadar1204** [comment]
will do;thank you
