### ISSUE TITLE
Update the Guidelines page

### ISSUE THREAD

**Issue by anikdhabal** [devvsakib/power-the-web#218]
**Describe the bug**
Guidelines page is not updated. In Backend Roadmap same content is present like frontend.

**To Reproduce**
1. Go to Guidelines
2. Click on backend Roadmap
3. See error

**Expected behavior**
All the roadmap should updated

**Screenshots**
<img width="1080" alt="Screenshot 2023-03-07 235314" src="https://user-images.githubusercontent.com/81948346/223514299-61754379-f0c3-4e3e-b9f7-64f8e5cd8d16.png">

**Comment by devvsakib** [comment]
we are working on it. it's just a demo purpose. thanks for rising an issue
