### ISSUE TITLE
[DOC]: add HTML CSS interview questions

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#224]
We are collecting often asked **interview** questions for Web Developers. Before adding questions and answers, please make sure if the question is already added or not. Use the search option to search your questions `Ctlr+F`/ `cmd+F`

path `src/json/interview/`

## Topics:
![image](https://user-images.githubusercontent.com/88339569/223778684-34cdfe02-9726-4d31-9843-513da4f1330a.png)

## How to add questions?
If you add HTML questions, then you have to use html tag, if CSS questions then use css, and so on.
![image](https://user-images.githubusercontent.com/88339569/223779892-8e8f62fc-7add-49e4-9181-3cf0e4239874.png)

**Comment by harsh472000** [comment]
@devvsakib i will do that can you assign to me?

**Comment by harsh472000** [comment]
@devvsakib i am not able to push my branch can you give me the permission to push my branch??

**Comment by devvsakib** [comment]
Please share what issue you faced @harsh472000

**Comment by harsh472000** [comment]
when i pushed my branch throws this error

remote: Permission to devvsakib/power-the-web.git denied to harsh472000.
fatal: unable to access 'https://github.com/devvsakib/power-the-web.git/': The requested URL returned error: 403

**Comment by harsh472000** [comment]
https://github.com/devvsakib/power-the-web/pull/234

this is my merge request Review and merge it

thank you.

**Comment by devvsakib** [comment]
Merged #234 

PR: @harsh472000

**Comment by devvsakib** [comment]
Merged #238 

PR: @Jrobbins973

**Comment by imlakshaychauhan** [comment]
Hey, #251 is my pull request  

please review and merge it 

thankyou.

**Comment by karthiknadar1204** [comment]
@devvsakib ,can i work on it too,could you please assign it to me

**Comment by devvsakib** [comment]
Assigned @karthiknadar1204

**Comment by karthiknadar1204** [comment]
have added 2 questions 2 both html and css,will initiate a pr soon

**Comment by karthiknadar1204** [comment]
@devvsakib ,could you guide me on how to sync changes between the fork repository and the existing remote repository,have made the changes but the fork for the same doesn't exist so unable to initiate a pull request.
