### ISSUE TITLE
fix typo mistake

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#230]
**Describe the bug**
Community typo mistake in readme.md file.
![image](https://user-images.githubusercontent.com/88339569/224120684-69c8f5c4-e6db-43ec-8022-3905f0401a14.png)

**To Reproduce**
fix the typo

**Comment by mukadas026** [comment]
Hello @devvsakib, please assign this issue to me I would love to take it.

**Comment by devvsakib** [comment]
Sure @mukadas026

**Comment by devvsakib** [comment]
do you want to take this @mukadas026 ?!!! I didn't received any response from you

**Comment by devvsakib** [comment]
@yugborana  are you still available to take this issue?

**Comment by mukadas026** [comment]
Yes, I'm still willing to take this, can you assign it to me

**Comment by mukadas026** [comment]
@devvsakib can I edit it directly on GitHub, my network isn't really strong and cloning the repo is taking forever

**Comment by devvsakib** [comment]
@mukadas026  yes you can. our repo has so many project and almost 130mb

**Comment by mukadas026** [comment]
Okay @devvsakib , thanks I'll get to it right away

**Comment by mukadas026** [comment]
All done now
