### ISSUE TITLE
Update repo size in READMEmd file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#241]
We have over 60+ projects in our repository🎉

Our repository size is 130.00 MiB

Please update the old size to 130.00 MiB
![image](https://user-images.githubusercontent.com/88339569/224424149-6034fd78-7110-4486-ab2f-1bc0425b0b4f.png)

Please add your details in `src/json/Contritbutors.json` file before PR.

**Comment by mukadas026** [comment]
@devvsakib Please assign me this issue.

**Comment by devvsakib** [comment]
Assigned @mukadas026

**Comment by devvsakib** [comment]
A PR maded for this issue #243
