### ISSUE TITLE
[DOC]: Add react interview question to JSON file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#242]
We are collecting often asked **interview** questions for Web Developers. Before adding questions and answers, please make sure if the question is already added or not. Use the search option to search your questions `Ctlr+F`/ `cmd+F`

path `src/json/interview/`

## Topics:
![image](https://user-images.githubusercontent.com/88339569/223778684-34cdfe02-9726-4d31-9843-513da4f1330a.png)

## How to add questions?
If you add HTML questions, then you have to use html tag, if CSS questions then use css, and so on.
![image](https://user-images.githubusercontent.com/88339569/223779892-8e8f62fc-7add-49e4-9181-3cf0e4239874.png)

**Comment by EslemOuederni** [comment]
Hey, I suppose we have to create src/json/javascriptinterview.json since I can't find it right ? The question and answer is copy pasted from online right ?

**Comment by devvsakib** [comment]
Im so sorry for the inconveniences. we changed the file name to
interviewquestions.json

**Comment by EslemOuederni** [comment]
Thank you!

**Comment by imlakshaychauhan** [comment]
Hey, https://github.com/devvsakib/power-the-web/pull/251 is my pull request

please review and merge it

thankyou.

**Comment by devvsakib** [comment]
Merged #251 

PR: @imlakshaychauhan

**Comment by karthiknadar1204** [comment]
@devvsakib ,i have a bunch of questions for react,could you please assign it to me

**Comment by devvsakib** [comment]
sure @karthiknadar1204

**Comment by karthiknadar1204** [comment]
Almost done,will merge pr by tomorrow night

**Comment by devvsakib** [comment]
Suree no problem, take your time @karthiknadar1204

**Comment by martinyis** [comment]
Hi, can I work on it?

**Comment by devvsakib** [comment]
yes. everyone can add questions @

**Comment by karthiknadar1204** [comment]
can we add more than one question. @devvsakib

**Comment by karthiknadar1204** [comment]
@devvsakib ,have added two questions on react js,have committed the changes and initiated a pr
Thank you

**Comment by EslemOuederni** [comment]
Hello @devvsakib I have added one single react question, but I see that it wasn't merged yet. Shall I be assigned to the issue first ?

**Comment by devvsakib** [comment]
I reviewed your PR @EslemOuederni , so sorry for the late reply. please check my comment. Thanks

**Comment by devvsakib** [comment]
Merged #277 

PR: @EslemOuederni
