### ISSUE TITLE
[FEAT]: add Nextjs interview question

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#259]
**Is your feature request related to a problem? Please describe.**
We are collecting often-asked interview questions for Web Developers. Before adding questions and answers, please make sure if the question is already added or not. Use the search option to search your questions Ctlr+F/ cmd+F
path `src/json/interview/`

Topics:
![image](https://user-images.githubusercontent.com/88339569/224535096-ba6e2d2e-a345-40ca-98cb-3027ae9ce4bd.png)

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json`

> If you do not add your details, your PR will be Close

**Comment by devvsakib** [comment]
Merged #260 
PR: @devvsakib

**Comment by sumit851** [comment]
plz assign this issue to  me . i am completely newbie also guide me to what i have to do.

**Comment by devvsakib** [comment]
Assigned @sumit851  and please read the issue description carefully.

**Comment by sumit851** [comment]
where to add my details

**Comment by devvsakib** [comment]
assigned @sumit851

**Comment by devvsakib** [comment]
in Contributors.json file @sumit851

**Comment by sumit851** [comment]
hey it cloning very slowly, how can i cancel cloning and delete the repo from my local device.

**Comment by devvsakib** [comment]
Our repository size is 130 Mb. it's cloning slow because of your internet speed. You can press Ctlr+C in the terminal to cancel @sumit851

**Comment by sumit851** [comment]
ok
