### ISSUE TITLE
[FEAT]: website UI/UX changing proposal

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#263]
**Is your feature request related to a problem? Please describe.**
I think we need to change the UI of the website. Need some better design as our repository traffic getting higher day by day and so many people using the PowerTheWeb website.

**Describe the solution you'd like**
Currently, we are using simple linear gradient background color. And for the doc page, the design is totally messy.
How about we change the UI/UX? We can design UI and submit it here. If you are a web designer then please help us🟩
Document page:
![image](https://user-images.githubusercontent.com/88339569/224749272-9e5ff3a2-6bfa-45ed-9be4-c04f89be1152.png)

**Describe alternatives you've considered**
We can change the background color and text to improve readability. At least we have to change the document page. If you have any ideas or designs please comment below🟩

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json`

> If you do not add your details, your PR will be Close

**Comment by munnokd** [comment]
You can use a glass-morphism design. It gives a great look at your website.

**Comment by devvsakib** [comment]
Document page design.
![Document page PowerTheWeb](https://user-images.githubusercontent.com/88339569/225009815-e575b2f1-57bb-4123-8030-ca90bb3c7317.png)

**Comment by devvsakib** [comment]
Figma: https://www.figma.com/community/file/1217459087811063862

**Comment by devvsakib** [comment]
![image](https://user-images.githubusercontent.com/88339569/225014336-09eb77aa-a4bb-4ae3-8787-3241157a5582.png)
![image](https://user-images.githubusercontent.com/88339569/225017409-51198ab7-9894-4ea8-8f22-03da139b8ffb.png)

Figma: https://www.figma.com/file/06SdUxcPFoIOqRZe0UnaH1/Untitled?node-id=0%3A1&t=FrJkGCdn5XngBqnt-1

**Comment by devraushan** [comment]
Can I do this ??

**Comment by devvsakib** [comment]
we are working on it, you can contribute and make changes @devraushan

**Comment by devraushan** [comment]
can i get exact color combinations to be used

**Comment by devvsakib** [comment]
Figma link provided

**Comment by devraushan** [comment]
did some changes Check if its fine or not.
PR #290
