### ISSUE TITLE
[FEAT]: The homepage navbar doesnt look eye catching and the ui is not well built 

### ISSUE THREAD

**Issue by ArslanYM** [devvsakib/power-the-web#264]
The homepage navbar doesnt look eye catching and the ui is not well built, the gradient doesnt also work well with the background of the page .

Solution proposed : 
Adding a better gradient to the navbar and adding some rounded edges to it , This will make the navbar look better and minimalistic 

It looks like this currently : 
![navbar](https://user-images.githubusercontent.com/104521101/224765543-4931beda-977a-49cd-ac7d-b85ce93665f9.png)

you can see how the navbar is a rectangle and doesnt suit the homepage .

If you feel the same , assign me this issue and ill work on it

**Comment by ArslanYM** [comment]
Great! @devvsakib  thanks

**Comment by devvsakib** [comment]
I think the full-width navbar and footer look better. Now we are using 1400px max width I guess!🤔

**Comment by ArslanYM** [comment]
Okay , what else do you think we can change?

**Comment by devvsakib** [comment]
I'm thinking to redesign the full website. but I'm very bad at designing😂.  

But do you have any idea for the Document page?
https://ptwa.vercel.app/guidelines/getstarted/Documents

**Comment by ArslanYM** [comment]
We can add a  overview of the project on the rightmost page div  when nothing is selected from the list. 
also i think chanign the ui of the left panel to something like this: 
![example](https://user-images.githubusercontent.com/104521101/224782567-1b864688-432a-4cd8-aee1-96ec3567f4db.png)

 will enhance the readability and user experience of it

**Comment by devvsakib** [comment]
wow, sure we can do the same💯 well designed, and improved UX

**Comment by ArslanYM** [comment]
How do you want to do it?

**Comment by devvsakib** [comment]
So far I did this
![image](https://user-images.githubusercontent.com/88339569/225048702-3724bee6-6df7-4a7f-a6f2-8d5a219b5545.png)

**Comment by devvsakib** [comment]
please review this PR #267

**Comment by karthiknadar1204** [comment]
@ArslanYM ,are you still working on this issue

**Comment by ArslanYM** [comment]
> @ArslanYM ,are you still working on this issue

No i am not. I will unassign myself

**Comment by karthiknadar1204** [comment]
@devvsakib ,could you please assign it to me,i was thinking of re-designing the front page to make it look more applealing with a more better color scheme to engage the users.
