### ISSUE TITLE
[FEAT]: Creating a better looking and more detailed frontend readme :  `basic frontend.md`

### ISSUE THREAD

**Issue by ArslanYM** [devvsakib/power-the-web#265]
the basic frontend.md is bland and doesnt have proper  details in it . 

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json`

> If you do not add your details, your PR will be Close

**Comment by Srinja333** [comment]
can i work on this?

**Comment by devvsakib** [comment]
@ArslanYM  do you want to work on this? or I should assign Srinja?

**Comment by ArslanYM** [comment]
Yes i want to want on this as mentioned above @devvsakib

**Comment by devvsakib** [comment]
You can work on other issues or you can create a new issue if you want to change something that improves our website. @Srinja333  Feel free to rise an issue. This issue assigned to Arslan
