### ISSUE TITLE
[FEAT]: delete css and js folder from assets folder

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#270]
Delete unused files

**Describe the solution you'd like**
Navigate to public/assets folder. delete CSS and js folder

![image](https://user-images.githubusercontent.com/88339569/225215738-f3d7366d-9894-4ddb-b3a0-5cf03b33e867.png)

**Describe alternatives you've considered**
null

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json`

> If you do not add your details, your PR will be Close

**Comment by Srinja333** [comment]
can i work on this?

**Comment by devvsakib** [comment]
Completed #278
