### ISSUE TITLE
[FEAT]: update CONTRIBUTING.md file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#276]
**Is your feature request related to a problem? Please describe.**
Update contributing guideline, We are getting PR from others who are not assigned to the issue. Please add a guideline about they can't make any PR if someone has already been assigned to a specific issue. If they make PR, their PR will be closed.

**Describe the solution you'd like**
Add a guide before adding project: [Link](https://github.com/devvsakib/power-the-web/blob/main/CONTRIBUTING.md)

![image](https://user-images.githubusercontent.com/88339569/225341561-145c4269-494f-40d6-be70-e4cf70294014.png)

**Describe alternatives you've considered**
Well written guide and understandable.

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json`

> If you do not add your details, your PR will be Close

**Comment by Srinja333** [comment]
can i work on this?

**Comment by devvsakib** [comment]
Assigned  @Srinja333
