### ISSUE TITLE
remove one section from readme file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#286]
**Is your feature request related to a problem? Please describe.**
remove this section from readme file

![image](https://user-images.githubusercontent.com/88339569/225415171-d6f43e6f-e51e-481f-9a6c-50b4c19e25d0.png)

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json` and you have to **MUST** read the contributing guideline before you start. [Here](https://github.com/devvsakib/power-the-web/blob/main/CONTRIBUTING.md)

> If you do not add your details, your PR will be Close

**Comment by devharsh007** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by devvsakib** [comment]
Assigned @devharsh007

**Comment by devvsakib** [comment]
navigate to this file `src/json/contributors.jsn`
Add your details here, make another PR

**Comment by devharsh007** [comment]
OKAY NOW I GOT THAT  THANKS.

**Comment by devvsakib** [comment]
Completed
