### ISSUE TITLE
[FEAT]: change word in readme file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#291]
**Is your feature request related to a problem? Please describe.**
Change this repository to project

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/88339569/225536094-f90f3c5c-df56-49bb-9d84-b13d5b64f726.png)

---
>**will be appreciated if beginners take this issue who want to get involved with open source**

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json` and you have to **MUST** read the contributing guideline before you start. [Here](https://github.com/devvsakib/power-the-web/blob/main/CONTRIBUTING.md)

> If you do not add your details, your PR will be Close

**Comment by GregoryNavasarkian** [comment]
Added PR #293

**Comment by devvsakib** [comment]
Completed #293
