### ISSUE TITLE
[BUG]: darkmode button overlape 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#302]
**Describe the bug**
In small device, dark mode button overlap with this icon.
![image](https://user-images.githubusercontent.com/88339569/225723536-d53be712-aa65-4f85-88fb-4134b41c1f76.png)

**To Reproduce**
set position for small device

**Smartphone (please complete the following information):**
 - Device: any
 - OS: null
 - Browser: all type
 - Version: any

## Checklist

- [x] I have read and followed the project's contributing guidelines
- [x] I have checked that this issue is not a duplicate of an existing issue
- [x] I have tested the bug in the latest version of the project
- [x] I have included all relevant information and examples in this issue description
- [x] I am available to collaborate on this issue and address any feedback from maintainers or other contributors

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json` and you have to **MUST** read the contributing guideline before you start.  [Read this Guideline Before you start](https://github.com/devvsakib/power-the-web/blob/main/CONTRIBUTING.md)
> If you do not add your details or not assigned to issue, your PR will be Close

**Comment by mukadas026** [comment]
@devvsakib please assign this issue to me

**Comment by devvsakib** [comment]
Sure @mukadas026

**Comment by devvsakib** [comment]
Complete #313
