### ISSUE TITLE
[BUG]: footer overlap in project page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#305]
**Describe the bug**
Footer is overlapping on the project page.
![image](https://user-images.githubusercontent.com/88339569/226095170-adcda7cb-d426-48e6-849f-dab8330a135c.png)s.

**To Reproduce**
Check height, overflow

**Expected behavior**
Place in the bottom

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome, firefox
 - Version  22

**Additional context**

## Checklist

- [x] I have read and followed the project's contributing guidelines
- [x] I have checked that this issue is not a duplicate of an existing issue
- [x] I have tested the bug in the latest version of the project
- [x] I have included all relevant information and examples in this issue description
- [x] I am available to collaborate on this issue and address any feedback from maintainers or other contributors

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json` and you have to **MUST** read the contributing guideline before you start.  [Read this Guideline Before you start](https://github.com/devvsakib/power-the-web/blob/main/CONTRIBUTING.md)
> If you do not add your details or not assigned to issue, your PR will be Close

**Comment by karthiknadar1204** [comment]
I would like to work on this issue

**Comment by devvsakib** [comment]
Assigned @karthiknadar1204

**Comment by otnansirk** [comment]
Is this issue not finished yet ?

**Comment by devvsakib** [comment]
karthik working on it @otnansirk

**Comment by otnansirk** [comment]
sorry, I have close my PR.

**Comment by karthiknadar1204** [comment]
i was about to merge a pr later tonight
never mind.
Thank you

**Comment by karthiknadar1204** [comment]
@otnansirk ,could you please share the change you applied ?

**Comment by otnansirk** [comment]
Yes. can you follow this link ? [commit](https://github.com/devvsakib/power-the-web/pull/310/commits/9a2b0afed16db3f1d13218be7148850f490ef5ba)

**Comment by kzamani44** [comment]
Please is the issue resolved yet? if no, I would like to work on this issue

**Comment by devvsakib** [comment]
Okk you can work on this issue @kzamani44
