### ISSUE TITLE
Adding a react portfolio to the projects.

### ISSUE THREAD

**Issue by theshrish46** [devvsakib/power-the-web#314]
Hey, I have built a **personal portfolio** project using **React** and **tailwind** can I add it to the project section? This is my first **open-source contribution** so am I allowed to do this?

**Comment by devvsakib** [comment]
Of course @theshrish46 . Assigned

**Comment by theshrish46** [comment]
Thankyou !!

**Comment by devvsakib** [comment]
Completed #315
