### ISSUE TITLE
Hey first of all thank you for mergin my project.

### ISSUE THREAD

**Issue by theshrish46** [devvsakib/power-the-web#319]
I tried to upload my profile to the contributor's list but it's not showing my profile. Everyone is using a different profile so can anybody tell me how to add a profile to your contributor's list?

**Comment by devvsakib** [comment]
your GitHub profile picture will appear here. No worries 🟢

**Comment by theshrish46** [comment]
Thanks a lot looking forward to contributing more to the project.
