### ISSUE TITLE
[Other]: UPDATE POWER-THE-WEB API

### ISSUE THREAD

**Issue by therealtmmy** [devvsakib/power-the-web#321]
### What would you like to share?
Kindly update the api attached to GetProjects.js so that other added projects can be displayed on web page.

**Comment by devvsakib** [comment]
it's not our created API. it's a GitHub API. If anyone add their project to PROJECTS folder, it will appear in web page

**Comment by therealtmmy** [comment]
Its not appearing. You might need to do something about it. There are tons of projects in that project folder that is not appearing on the web page. I hope you understand

**Comment by therealtmmy** [comment]
I like you to check for confirmation sake.
