### ISSUE TITLE
Working on a new project and looking to add it to the repo

### ISSUE THREAD

**Issue by theshrish46** [devvsakib/power-the-web#327]
Hey, I am working on a business portfolio website project using simple HTML and CSS. I will be completing it but today and looking forward to merge it today itself can you please assign it to me?

**Comment by devvsakib** [comment]
Sure,

**Comment by theshrish46** [comment]
Thank you !

**Comment by theshrish46** [comment]
Thank you for merging the project. Anything else I can contribute to the repo? Like helping someone or anything like that..?

**Comment by devvsakib** [comment]
you can add some interview question

**Comment by theshrish46** [comment]
Thank you
