### ISSUE TITLE
[FEAT]: contributor card

### ISSUE THREAD

**Issue by otnansirk** [devvsakib/power-the-web#340]
**Is your feature request related to a problem? Please describe.**
Based on what I saw the discussion here [We can add projects card](https://github.com/devvsakib/power-the-web/discussions/152).

**Describe the solution you'd like**
My solution is we will added the contributor card to list of /contributors page. on the card of list contributor will added one button let's say `my card` (this name will not necessarily be the same). this button will show the card like this :

Example : 
![Screenshot from 2023-03-29 22-46-23](https://user-images.githubusercontent.com/30102523/228607597-2f85e9be-fe44-44a7-8022-c939f9cd3d9d.png)

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json` and you have to **MUST** read the contributing guideline before you start.  [Read this Guideline Before you start](https://github.com/devvsakib/power-the-web/blob/main/CONTRIBUTING.md)
> If you do not add your details or assigned to issue, your PR will be Close

**Comment by devvsakib** [comment]
Completed #345
