### ISSUE TITLE
[DOC] Create contributor card documentation

### ISSUE THREAD

**Issue by otnansirk** [devvsakib/power-the-web#352]
## Description

Depend on this [dicsussion](https://github.com/devvsakib/power-the-web/discussions/152). 

We successfully add contributor card feature. and I hope all of you guys, you can update your profile on [Contributors.json](https://github.com/devvsakib/power-the-web/blob/main/src/json/Contributors.json) and add your project url to your profile. with this you can see your project on your contributor card, and than you can generate or download you contributor card. 
you can follow this [contributor card docs](https://github.com/devvsakib/power-the-web/blob/main/docs/contributor-card.md) to achieve it.

Feel free to update the [contributor card documentation](https://github.com/devvsakib/power-the-web/blob/main/docs/contributor-card.md) to make it easier to understand.

Thank you.

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json` and you have to **MUST** read the contributing guideline before you start.  [Read this Guideline Before you start](https://github.com/devvsakib/power-the-web/blob/main/CONTRIBUTING.md)
> If you do not add your details or are not assigned to issue, your PR will be Close

**Comment by nelsonuprety1** [comment]
Hi there,

I've made some changes to the contributors.md file #369  in order to make it easier to read and understand. I added some formatting and organization to the steps, as well as some additional motivation for contributors to join the project.

Please take a look and let me know if you have any feedback or suggestions for further improvements.

Thank you!

**Comment by otnansirk** [comment]
great, thanks. 

your PR has been merged

**Comment by devvsakib** [comment]
Completed #369

**Comment by nelsonuprety1** [comment]
Cheers guys🎉
