### ISSUE TITLE
[FEAT]: improve mobile navbar

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#360]
**Is your feature request related to a problem? Please describe.**
Mobile navbar doesn't look good. We can add some animation when the user toggles the menu.
![image](https://user-images.githubusercontent.com/88339569/230646928-b993c6c9-3c2a-43cb-a9d1-d46e454a0f64.png)

**Describe the solution you'd like**
Add a cool animation for toggles, and Redesign the mobile nav according to you. 

**IMPORTANT**
If it's your first Contribution to this project, please add your details to the Contributors file
File Path: `src/json/Contributors.json` and you have to **MUST** read the contributing guideline before you start.  [Read this Guideline Before you start](https://github.com/devvsakib/power-the-web/blob/main/CONTRIBUTING.md)
> If you do not add your details or assigned to issue, your PR will be Close

**Comment by Srujan1527** [comment]
Assign it to me @devvsakib

**Comment by devvsakib** [comment]
Assigned @Srujan1527

**Comment by karthiknadar1204** [comment]
@devvsakib ,can i also work on this issue? I had some good ideas to implement

**Comment by Srujan1527** [comment]
Sure we will work together

**Comment by nelsonuprety1** [comment]
Hello, can i also work on the issue? Thank you

**Comment by devvsakib** [comment]
Great Team🟢

**Comment by karthiknadar1204** [comment]
<img width="571" alt="Screenshot 2023-04-08 at 10 24 37 PM" src="https://user-images.githubusercontent.com/95973644/230733495-191b2d84-7a39-4b70-b625-1717391275f5.png">


I have aligned the elements of the mobile navbar to the center,is this fine or wold you like to change it? @devvsakib

**Comment by karthiknadar1204** [comment]
should i initiate a pr @devvsakib ?

**Comment by devvsakib** [comment]
No, the centered menu doesn't look great.

**Comment by karthiknadar1204** [comment]
Fine,will change it
any suggestions @devvsakib @Srujan1527

**Comment by karthiknadar1204** [comment]
@devvsakib ,was thinking of adding a drawer effect that pops up from left side when we click the burger-menu occupying the left-height,will try implementing and share it once again

**Comment by devvsakib** [comment]
great!

**Comment by karthiknadar1204** [comment]
can i incorporate an extrenal css framework to simplify the work like tailwind css @devvsakib

**Comment by devvsakib** [comment]
of course, we can use it.

**Comment by karthiknadar1204** [comment]
Have begun the work,will merge a pr by tuesday for sure

Thank you

**Comment by otnansirk** [comment]
Is this case over ? I don't see any change in mobile navbar.
