### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by theshrish46** [devvsakib/power-the-web#381]
## I have built a simple JavaScript Timer can I push it to the repo and get my PR accepted.

**Comment by theshrish46** [comment]
Thank you

**Comment by theshrish46** [comment]
Can you please tell me how to remove the .git file this error is the first time for me.

**Comment by otnansirk** [comment]
You can remove .git from terminal. Like this if done on a linux os.
```
rm -rf .git
```
And you can find other way in other os.
