### ISSUE TITLE
[FEATURE] add a Quiz Application using reactjs

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#42]
build a simple Quiz Application with react and add it to 'PROJECTS' folder.

Its a good practice for beginners, so lets smash it.

**Comment by sandilya27** [comment]
I want to work on this please assign it to me?

**Comment by devvsakib** [comment]
> I want to work on this please assign it to me?

assigned, don't forget to give us start😉

**Comment by devvsakib** [comment]
hi @sandilya27  is there any update?

**Comment by sa2789** [comment]
There some delay due to my midsem exam but it will be completed till monday

**Comment by devvsakib** [comment]
> 

ohho, focus on exam first. good luck

**Comment by sandilya27** [comment]
Hey I have a query you want quiz app with prewritten question or it fetch question from api

**Comment by devvsakib** [comment]
> Hey I have a query you want quiz app with prewritten question or it fetch question from api

it doesn't matter, just need an app😉

**Comment by sandilya27** [comment]
ok started working on it you will get it by tomorrow

**Comment by Mansi168** [comment]
Hey @devvsakib i would like to work on this issue...kindly assign it to me..!

**Comment by devvsakib** [comment]
sure, all yours @Mansi168

**Comment by Saikat-Mandal** [comment]
hey @devvsakib is the issue solved ?

**Comment by devvsakib** [comment]
> hey @devvsakib is the issue solved ?

no, @Mansi168 may be working on it. you also can work on it. if you want I can assign you too.

**Comment by Saikat-Mandal** [comment]
@devvsakib Ok then i will work on. Thanks !

**Comment by Mansi168** [comment]
> > hey @devvsakib is the issue solved ?
> 
> no, @Mansi168 may be working on it. you also can work on it. if you want I can assign you too.

yes I m working on this

**Comment by Saikat-Mandal** [comment]
Hey @Mansi168 You want to work together ? if not then you just open a PR and i will not open one. Side by side i will also be doing for learning purposes, if you finish first i will not be opening a PR.

**Comment by devvsakib** [comment]
Please you guys can work on this issue, we are collecting projects for the web developers. We need as many as projects we can.

There can be the same project, but their structure may be different right? For example, we have more than one to-do app in our projects folder.  

Let's work together😉

**Comment by Mansi168** [comment]
okay as @devvsakib said there can be more than one projects of the same kind...so @Saikat-Mandal we both can work independently.

**Comment by devvsakib** [comment]
Close this issue due to no response from contributors
