### ISSUE TITLE
hacktoberfest PR, PR your project 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#54]
PR your projects to "PROJECTS" folder and get accepted by hacktoberfest.
I will label your PR as hacktoberfest.
PR as much as you want, unlimited assign to this issue. don't forget to add your copyright to your projects Footer

**Comment by pratyushkr11** [comment]
I want to add a react project. Can u please assign me this issue.

**Comment by devvsakib** [comment]
> I want to add a react project. Can u please assign me this issue.

sure

**Comment by mtahashahid** [comment]
I want to add covid19 tracker project in Reactjs. Can you please assign this to me?

**Comment by devvsakib** [comment]
> I want to add covid19 tracker project in Reactjs. Can you please assign this to me?

assigned

**Comment by Git-Akshat01** [comment]
Hi! @devvsakib I want to add a full stack project can you please assign this to me?

**Comment by devvsakib** [comment]
> Hi! @devvsakib I want to add a full stack project can you please assign this to me?

assigned

**Comment by ManavMalhotra** [comment]
can i add my node js file organizer which sort the files?

**Comment by devvsakib** [comment]
> can i add my node js file organizer which sort the files?

sure, assigned

**Comment by ManavMalhotra** [comment]
I have added my project https://github.com/ManavMalhotra/hacktoberfest-react-project/pull/1

**Comment by devvsakib** [comment]
> I have added my project [ManavMalhotra#1](https://github.com/ManavMalhotra/hacktoberfest-react-project/pull/1)

I cant see your PR, did you pr?
