### ISSUE TITLE
add a react project

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#7]
## add a simple react counter app.
increase and decrease count. should be count > 0, 
count !=0 or count<0

**Comment by piyush-mahajan** [comment]
hey, can you please assign me this issue? I would love to work on this project.

**Comment by codeansh20** [comment]
Can u assign this task to me

**Comment by devvsakib** [comment]
> Can u assign this task to me

done

**Comment by YugalPradhan** [comment]
hey can u assign  me this

**Comment by pjyoti121** [comment]
Please assign me this issue

**Comment by devvsakib** [comment]
> Please assign me this issue

assigned

**Comment by dipankurverma** [comment]
Hi, can you please assign me for the issue!

**Comment by devvsakib** [comment]
> Hi, can you please assign me for the issue!

ok
