### ISSUE TITLE
[BRANCH - "convert-react"] add existing profile card to react website

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#90]
## Navigate to folder
**Check 2nd Branch, name- convert-react
Clone this, and navigate to main-website folder, this is the main website we are converting into react website after you have done, PR to convert-react branch, not in the "main" branch. Add your details to contributors.json file.**

## Feature?
add contributors card

## Bug?
No

Task:
We have contributors card design, go [there](https://devvsakib.github.io/hacktoberfest-react-project/contributor.html)
add this card to contributors page

You can join our discord server - let's build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by yes-im-harsh** [comment]
Please assign this to me @devvsakib

**Comment by devvsakib** [comment]
> Please assign this to me @devvsakib

assigned

**Comment by yes-im-harsh** [comment]
@devvsakib check PR: #99
