### ISSUE TITLE
[BRANCH - "convert-react"] menu not showing when click on icon

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#91]
## Navigate to the folder
**Check 2nd Branch, name- convert-react
Clone this, and navigate to main-website folder, this is the main website we are converting into react website after you have done, PR to the convert-react branch, not in the "main" branch. Add your details to contributors.json file.**

## Bug?
Menu not showing when we click on icon
![image](https://user-images.githubusercontent.com/88339569/197375972-e9967c5d-c1f6-49e3-8035-ace74ce9a307.png)

Task:
Manu should show and hide when we click

You can join our discord server - let's build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by RXBlade** [comment]
I'll try and help

**Comment by devvsakib** [comment]
> I'll try and help

ok

**Comment by dipankurverma** [comment]
Hi, is this issue still open?

**Comment by devvsakib** [comment]
hi @dipankurverma  thanks for mentioning it. This issue is completed but unfortunately not closed. Thank you again
